services:
  fastapi:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    env_file:
      - .env
    command: poetry run celery -A fastapi_assignment.celery_config.celery worker --loglevel=info -P solo
    depends_on:
      - redis
      - mongodb

  test_runner:
    build: .
    env_file:
      - .env
    command: poetry run pytest tests/ --maxfail=3 --disable-warnings -v
    depends_on:
      - mongodb
      - redis
      - fastapi

volumes:
  mongo_data:
