services:
  fastapi:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URL=mongodb://mongodb:27017/assignment_db
      - REDIS_URL=redis://redis:6379
      - DB_NAME=assignment_db
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    env_file:
      - .env
    command: poetry run celery -A fastapi_assignment.celery_config.celery worker --loglevel=info -P solo
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/assignment_db
      - REDIS_URL=redis://redis:6379
      - DB_NAME=assignment_db

    restart: unless-stopped

volumes:
  mongo_data:
